<br /><br />
<div id="view-content">
<form action="contact" method="post" >
<fieldset><legend>User Data</legend>
<label for="email">Your E-mail Address:</label><br />
<input type="text" name="email" value="" size="25" /><br />
<label for="message">Your Message:</label><br />
<textarea name="message" cols="30" rows="10"></textarea><br />
<input type="submit" name="submit" value="Contact Us!" />
</fieldset>
</form>

</div>